-- stg_2021, fpl_2021 and backup might be given other names for later seasons
-- (these represent stg_schema, main_schema and backup_schema)
CREATE TABLE stg_2021.stg_teams (
    id                         int primary key,
    code                       int,
    draw                       int,
    form                       int,
    loss                       int,
    name                       varchar(30),
    played                     int,
    points                     int,
    position                   int,
    short_name                 varchar(3),
    strength                   int,
    team_division              varchar(30),
    unavailable                boolean,
    win                        int,
    strength_overall_home      int,
    strength_overall_away      int,
    strength_attack_home       int,
    strength_attack_away       int,
    strength_defence_home      int,
    strength_defence_away      int,
    pulse_id                   int
);

CREATE TABLE stg_2021.stg_player_static (
    id            int primary key,
    chance_of_playing_next_round   int,
    chance_of_playing_this_round   int,
    code   int,
    cost_change_event   int,
    cost_change_event_fall   int,
    cost_change_start   int,
    cost_change_start_fall   int,
    dreamteam_count   int,
    element_type   int,
    ep_next   numeric,
    ep_this   numeric,
    event_points   int,
    first_name   varchar(255),
    form  numeric,
    in_dreamteam   boolean,
    news   text,
    news_added   timestamptz,
    now_cost   int,
    photo   varchar(30),
    points_per_game   numeric,
    second_name   varchar(255),
    selected_by_percent   numeric,
    special   boolean,
    squad_number   varchar(10),
    status   varchar(10),
    team   int,
    team_code   int,
    total_points   int,
    transfers_in   int,
    transfers_in_event   int,
    transfers_out   int,
    transfers_out_event   int,
    value_form   numeric,
    value_season   numeric,
    web_name   varchar(255),
    minutes   int,
    goals_scored   int,
    assists   int,
    clean_sheets   int,
    goals_conceded   int,
    own_goals   int,
    penalties_saved   int,
    penalties_missed   int,
    yellow_cards   int,
    red_cards   int,
    saves   int,
    bonus   int,
    bps   int,
    influence   numeric,
    creativity   numeric,
    threat   numeric,
    ict_index   numeric,
    influence_rank   int,
    influence_rank_type   int,
    creativity_rank   int,
    creativity_rank_type   int,
    threat_rank   int,
    threat_rank_type   int,
    ict_index_rank   int,
    ict_index_rank_type   int,
    corners_and_indirect_freekicks_order   int,
    corners_and_indirect_freekicks_text   text,
    direct_freekicks_order   int,
    direct_freekicks_text   text,
    penalties_order   int,
    penalties_text   text
);

CREATE TABLE stg_2021.stg_element_types (
    id                      int primary key,
    plural_name             varchar(30),
    plural_name_short       varchar(3),
    singular_name           varchar(30),
    singular_name_short     varchar(3),
    squad_select            int,
    squad_min_play          int,
    squad_max_play          int,
    ui_shirt_specific       boolean,
    sub_positions_locked    varchar(30),
    element_count           int
);

CREATE TABLE stg_2021.stg_fixtures (
    code                      int primary key,
    event                     int,
    finished                  boolean,
    finished_provisional      boolean,
    id                        int,
    kickoff_time              timestamptz,
    minutes                   int,
    provisional_start_time    boolean,
    started                   boolean,
    team_a                    int,
    team_a_score              int,
    team_h                    int,
    team_h_score              int,
    team_h_difficulty         int,
    team_a_difficulty         int,
    pulse_id                  int
);

CREATE TABLE stg_2021.stg_player_history (
    element               int, 
    fixture               int,
    opponent_team         int,
    total_points          int,
    was_home              boolean,
    kickoff_time          timestamptz,
    team_h_score          int,
    team_a_score          int,
    round                 int,
    minutes               int,
    goals_scored          int,
    assists               int,
    clean_sheets          int,
    goals_conceded        int,
    own_goals             int,
    penalties_saved       int,
    penalties_missed      int,
    yellow_cards          int,
    red_cards             int,
    saves                 int,
    bonus                 int,
    bps                   int,
    influence             numeric,
    creativity            numeric,
    threat                numeric,
    ict_index             numeric,
    value                 int,
    transfers_balance     int,
    selected              int,
    transfers_in          int,
    transfers_out         int,
    PRIMARY KEY (element, fixture)
);

CREATE TABLE fpl_2021.player_history (
    element                 int,
    fixture                 int,
    opponent_team           int,
    total_points            int,
    was_home                boolean,
    kickoff_time            timestamptz,
    team_h_score            int,
    team_a_score            int,
    round                   int,
    minutes                 int,
    goals_scored            int,
    assists                 int,
    clean_sheets            int,
    goals_conceded          int,
    own_goals               int,
    penalties_saved         int,
    penalties_missed        int,
    yellow_cards            int,
    red_cards               int,
    saves                   int,
    bonus                   int,
    bps                     int,
    influence               numeric,
    creativity              numeric,
    threat                  numeric,
    ict_index               numeric,
    value                   int,
    transfers_balance       int,
    selected                int,
    transfers_in            int,
    transfers_out           int,
    web_name                varchar(255),
    team                    int,
    position                varchar(3),
    name_own_team           varchar(3),
    strength_own_team       int,
    name_opponent_team      varchar(3),
    strength_opponent_team  int,
    finished                boolean NOT NULL,
    time_inserted           timestamptz,
    PRIMARY KEY (element, fixture)
);

-- Should be identical as fpl_2021.player_history
CREATE TABLE backup.player_history (
    element                 int,
    fixture                 int,
    opponent_team           int,
    total_points            int,
    was_home                boolean,
    kickoff_time            timestamptz,
    team_h_score            int,
    team_a_score            int,
    round                   int,
    minutes                 int,
    goals_scored            int,
    assists                 int,
    clean_sheets            int,
    goals_conceded          int,
    own_goals               int,
    penalties_saved         int,
    penalties_missed        int,
    yellow_cards            int,
    red_cards               int,
    saves                   int,
    bonus                   int,
    bps                     int,
    influence               numeric,
    creativity              numeric,
    threat                  numeric,
    ict_index               numeric,
    value                   int,
    transfers_balance       int,
    selected                int,
    transfers_in            int,
    transfers_out           int,
    web_name                varchar(255),
    team                    int,
    position                varchar(3),
    name_own_team           varchar(3),
    strength_own_team       int,
    name_opponent_team      varchar(3),
    strength_opponent_team  int,
    finished                boolean NOT NULL,
    time_inserted           timestamptz,
    PRIMARY KEY (element, fixture)
);


-- Should be identical as fpl_2021.player_history
CREATE TABLE backup.player_history (
    element                 int,
    fixture                 int,
    opponent_team           int,
    total_points            int,
    was_home                boolean,
    kickoff_time            timestamptz,
    team_h_score            int,
    team_a_score            int,
    round                   int,
    minutes                 int,
    goals_scored            int,
    assists                 int,
    clean_sheets            int,
    goals_conceded          int,
    own_goals               int,
    penalties_saved         int,
    penalties_missed        int,
    yellow_cards            int,
    red_cards               int,
    saves                   int,
    bonus                   int,
    bps                     int,
    influence               numeric,
    creativity              numeric,
    threat                  numeric,
    ict_index               numeric,
    value                   int,
    transfers_balance       int,
    selected                int,
    transfers_in            int,
    transfers_out           int,
    web_name                varchar(255),
    team                    int,
    position                varchar(3),
    name_own_team           varchar(3),
    strength_own_team       int,
    name_opponent_team      varchar(3),
    strength_opponent_team  int,
    finished                boolean NOT NULL,
    time_inserted           timestamptz,
    PRIMARY KEY (element, fixture)
);

CREATE TABLE fpl_2021.prediction (
    element                 int,
    round                   int,
    points                  numeric,
    points_cumulative       numeric,
    PRIMARY KEY (element, round)
);
